#!/bin/bash
# This takes the initial access log files and produces a single file that 
# has IP date/time for each metainfo access entry.

grep $1  `ls -1 access.log* | sort -n -k 1.12 -r` | awk -F: '{print $2, $3, $4, $5}' | awk '{printf("%s %s:%s:%s:%s\n",$1,$4,$5,$6,$7);}'  | tr -d '[' > ipdate.filtered.log
